import Head from "next/head";
import ArticlesTable from "../../components/articles/table";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { deleteArticleAction } from "../../redux/reducer";
import toast from "react-hot-toast";
import DeleteConfirmation from "../../components/articles/delete-confirmation";

const Articles = () => {
  const dispatch = useDispatch();
  const articleIdToDelete = useSelector((state) => state.app.articles.deleteId);

  useEffect(() => {
    if (articleIdToDelete) {
      toast((t) => (
        <DeleteConfirmation
          id={articleIdToDelete}
          onConfirm={() => toast.dismiss(t.id)}
          onCancel={() => {
            toast.dismiss(t.id);
            dispatch(deleteArticleAction(null));
          }}
        />
      ));
    }
  }, [dispatch, articleIdToDelete]);

  return (
    <div>
      <Head>
        <title>Manage Articles : MetaAdmin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container px-4 md:px-10 lg:px-20">
          <div className="py-10 flex align-middle justify-between">
            <h2 className="text-lg font-normal mb-5">Manage Articles</h2>
            <Link
              href="/articles/create"
              className="flex items-center bg-gray-600 h-10 px-8 rounded-md hover:bg-gray-700 hover:border-indigo-500"
            >
              Add
            </Link>
          </div>
        </div>
        <div className="container px-4 md:px-10 lg:px-20">
          <div className="bg-gray-700 rounded-2">
            <ArticlesTable />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Articles;
