import Head from "next/head";
import ResourcesTable from "../../components/resources/table";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { deleteResourceAction } from "../../redux/reducer";
import toast from "react-hot-toast";
import DeleteConfirmation from "../../components/resources/delete-confirmation";

const Resources = () => {
  const dispatch = useDispatch();
  const resourceIdToDelete = useSelector(
    (state) => state.app.resources.deleteId
  );

  useEffect(() => {
    if (resourceIdToDelete) {
      toast((t) => (
        <DeleteConfirmation
          id={resourceIdToDelete}
          onConfirm={() => toast.dismiss(t.id)}
          onCancel={() => {
            toast.dismiss(t.id);
            dispatch(deleteResourceAction(null));
          }}
        />
      ));
    }
  }, [dispatch, resourceIdToDelete]);

  return (
    <div>
      <Head>
        <title>Manage Resources : MetaAdmin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container px-4 md:px-10 lg:px-20">
          <div className="py-10 flex align-middle justify-between">
            <h2 className="text-lg font-normal mb-5">Manage Resources</h2>
            <Link
              href="/resources/create"
              className="flex items-center bg-gray-600 h-10 px-8 rounded-md hover:bg-gray-700 hover:border-indigo-500"
            >
              Add
            </Link>
          </div>
        </div>
        <div className="container px-4 md:px-10 lg:px-20">
          <div className="bg-gray-700 rounded-2">
            <ResourcesTable />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Resources;
